/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Bill;
import Entity.BillDetail;
import Entity.Product;
import Entity.User;
import Model.BillDAO;
import Model.ProductDAO;
import Helper.JdbcHelper;
import Model.LangDAO;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author ADMIN
 */
public class BillController extends javax.swing.JDialog {

    /**
     * Creates new form BillController
     */
    Login parent;
    JdbcHelper dbConn = null;
    Connection conn = null;
    User user = null;
    Locale loca = null;
    ResourceBundle bun = null;
    ProductDAO productDAO = new ProductDAO();    
    Product product = null;
    List<BillDetail> bill = new ArrayList<>();
    DefaultListModel<String> model = new DefaultListModel<>();

    public BillController(java.awt.Frame parent, boolean modal, JdbcHelper dbconn, User u) {
        super(parent, modal);
        try {
            initComponents();
            this.dbConn = dbconn;
            this.user = u;
            String lang = new LangDAO().getLang();
            if (lang.equals("EN")) {
                this.loca = new Locale("en", "EN");
                this.bun = ResourceBundle.getBundle("Translation.message", loca);
            } else {
                this.loca = new Locale("vi", "VI");
                this.bun = ResourceBundle.getBundle("Translation.message", loca);
            }
            
            seller.setText("Seller: " + this.user.getName());
            lbDate.setText(java.time.LocalDateTime.now().toString());
            setLanguage();
            this.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(BillController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seller = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        btNewBill = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPay = new javax.swing.JLabel();
        btAddtoBill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduct = new javax.swing.JList<>();
        btCheckCode = new javax.swing.JButton();
        btCreateBill = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbSeller = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        seller.setText("Seller: ");

        lb.setText("Date: ");

        jLabel3.setText("Product code");

        txtCode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Quantity");

        jLabel5.setText("Price");

        lbPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btNewBill.setText("New Bill");
        btNewBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewBillActionPerformed(evt);
            }
        });

        jLabel6.setText("Discount");

        lbDiscount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Price need to pay");

        lbPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btAddtoBill.setText("Add to bill");
        btAddtoBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddtoBillActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listProduct);

        btCheckCode.setText("Check code");
        btCheckCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCheckCodeActionPerformed(evt);
            }
        });

        btCreateBill.setText("Create bill");
        btCreateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCreateBillActionPerformed(evt);
            }
        });

        label.setText("Total: ");

        lbtotal.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(lbPay, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCode)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(btCheckCode))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btAddtoBill)
                        .addGap(59, 59, 59)
                        .addComponent(btNewBill)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label)
                        .addGap(18, 18, 18)
                        .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239)
                        .addComponent(btCreateBill)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btCheckCode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(lbPay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAddtoBill)
                            .addComponent(btNewBill)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btCreateBill)
                .addGap(32, 32, 32))
        );

        jLabel8.setText("List of Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seller)
                        .addGap(18, 18, 18)
                        .addComponent(lbSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbSeller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewBillActionPerformed
        txtCode.setText("");
        txtQuantity.setText("");
        lbDiscount.setText("");
        lbPay.setText("");
        lbtotal.setText("0");
        lbPrice.setText("");
        this.bill.clear();
        this.model.clear();
        listProduct.setModel(this.model);
        lbDate.setText(java.time.LocalDateTime.now().toString());
    }//GEN-LAST:event_btNewBillActionPerformed

    private void btCheckCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCheckCodeActionPerformed
        try {
            int code = Integer.parseInt(txtCode.getText());
            Product p = productDAO.getProductById(code);
            if(p==null){
                JOptionPane.showMessageDialog(this, "Not found this code");
            }else{
                lbPrice.setText(String.valueOf(p.getSellPrice()));
                lbDiscount.setText(String.valueOf(p.getDiscount()));
                Float price = Float.parseFloat(lbPrice.getText());
                Float discount = Float.parseFloat(lbDiscount.getText());
                Float needPay = price+price*discount;
                lbPay.setText(String.valueOf(needPay));
                this.product = p;
            }
        } catch (Exception ex) {
            Logger.getLogger(BillController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCheckCodeActionPerformed

    private void btAddtoBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddtoBillActionPerformed
        if(txtCode.getText().isEmpty() || txtQuantity.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter code and quantity, please");
        }else{
            if(lbPrice.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Check code first");
            }else{                
                float sellPrice =Float.parseFloat(lbPrice.getText()) ;
                int quantity = Integer.parseInt(txtQuantity.getText());
                this.bill.add(new BillDetail(this.product, quantity, sellPrice));
                float total = Float.parseFloat(lbtotal.getText());
                total+=sellPrice*quantity;
                lbtotal.setText(String.valueOf(total));
                model.addElement(this.product.getName()+" "+quantity);
                listProduct.setModel(this.model);
            }
        }
    }//GEN-LAST:event_btAddtoBillActionPerformed

    private void btCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCreateBillActionPerformed
        try {
            String date = lbDate.getText();
            Float total = Float.parseFloat(lbtotal.getText());
            int n = new BillDAO().createBill(this.user, date, total);
            if(n>0){
                JOptionPane.showMessageDialog(this, "add bill successed");
                Bill b = new BillDAO().getBill(date, this.user.getId());
                for (int i = 0; i < this.bill.size(); i++) {
                    new BillDAO().insertBillDetail(this.bill.get(i), b);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(BillController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btCreateBillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddtoBill;
    private javax.swing.JButton btCheckCode;
    private javax.swing.JButton btCreateBill;
    private javax.swing.JButton btNewBill;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbPay;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSeller;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JList<String> listProduct;
    private javax.swing.JLabel seller;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void setLanguage() {        
    }
}
