/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Product;
import Entity.StockInOutDetail;
import Entity.User;
import Model.ProductDAO;
import Helper.JdbcHelper;
import Model.LangDAO;
import Model.StockDAO;
import java.sql.Connection;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class InventoryStaffController extends javax.swing.JDialog {

    /**
     * Creates new form InventoryStaffController
     */
    Login parent;
    JdbcHelper dbConn = null;
    Connection conn = null;
    User user = null;
    Locale loca = null;
    ResourceBundle bun = null;
    ProductDAO dao = new ProductDAO();

    public InventoryStaffController(java.awt.Frame parent, boolean modal, JdbcHelper dbconn, User u) {
        super(parent, modal);
        try {
            initComponents();
            this.dbConn = dbconn;
            this.user = u;
            String lang = new LangDAO().getLang();
            if (lang.equals("EN")) {
                this.loca = new Locale("en", "EN");
                this.bun = ResourceBundle.getBundle("Translation.message", loca);
            } else {
                this.loca = new Locale("vi", "VI");
                this.bun = ResourceBundle.getBundle("Translation.message", loca);
            }
            
            lbStaff.setText(this.user.getName());
            lbDate.setText(java.time.LocalDate.now().toString());
            setLanguage();
            this.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(InventoryStaffController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbStaff = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btSearch = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lbOut = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btInsert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Staff: ");

        jLabel3.setText("Date");

        jLabel2.setText("Product ID");

        btSearch.setText("Search");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount in");

        jLabel5.setText("Amount Out");

        lbOut.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Quantity Stock");

        lbQuantity.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btInsert.setText("Insert");
        btInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(lbDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btInsert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btSearch)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btInsert)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbOut, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        try {
            int id = Integer.parseInt(txtId.getText());
            Product p = dao.getProductById(id);
            if (p == null) {
                JOptionPane.showMessageDialog(this, "Not found");
            } else {
                StockInOutDetail st = new StockDAO().getStockofProduct(p);
                if (st != null) {
                    lbOut.setText(String.valueOf(st.getAmountOut()));
                    txtIn.setText(String.valueOf(st.getAmountIn()));
                    lbQuantity.setText(String.valueOf(st.getQuantityStock()));
                }else{
                    lbOut.setText("0");
                    txtIn.setText("0");
                    lbQuantity.setText("0");
                }
                
            }
        } catch (Exception ex) {
            Logger.getLogger(InventoryStaffController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void btInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertActionPerformed
        try {
            int pid = Integer.parseInt(txtId.getText());
            Product p = dao.getProductById(pid);
            String date = lbDate.getText();
            int in = Integer.parseInt(txtIn.getText());
            int out = Integer.parseInt(lbOut.getText());
            int quantity = Integer.parseInt(lbQuantity.getText());
            StockInOutDetail st = new StockDAO().searchStock(date, pid);
            StockInOutDetail stLast = new StockDAO().getStockofProduct(p);
            int quantityLast = 0;
            if(stLast!=null) quantityLast = stLast.getQuantityStock();
            if (st == null) {
                // nhập hàng pid lần 1 trong ngày date
                new StockDAO().createStockIn(date, p, in, quantityLast + in);
            } else {
                // nhập hàng pid lần thứ 2 trở đi trong ngày date
                if(stLast.getDate().equals(date)) new StockDAO().updateStockIn(st, in+stLast.getAmountIn(), quantity+in);
                else new StockDAO().updateStockIn(st, in, quantityLast + in);
            }
        } catch (Exception ex) {
            Logger.getLogger(InventoryStaffController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInsert;
    private javax.swing.JButton btSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbOut;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbStaff;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIn;
    // End of variables declaration//GEN-END:variables

    private void setLanguage() {
    }
}
