/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Product;
import Model.ProductDAO;
import Helper.JdbcHelper;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class ProducManagement extends javax.swing.JDialog {
    JdbcHelper dbConn = null;
    Locale loca = null;
    ResourceBundle bun = null;
    /**
     * Creates new form ProducManagement
     */
    public ProducManagement(java.awt.Frame parent, boolean modal, JdbcHelper dbconn, Locale loca, ResourceBundle bun) {
        super(parent, modal);
        initComponents();
        this.dbConn = dbconn;
        initProduct();
        this.loca = loca;
        this.bun = bun;
        setLanguage();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        btDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbCategory = new javax.swing.JLabel();
        lbProduct = new javax.swing.JLabel();
        lbUnitPrice = new javax.swing.JLabel();
        lbDiscount = new javax.swing.JLabel();
        lbOrigin = new javax.swing.JLabel();
        lbSellPrice = new javax.swing.JLabel();
        btAdd = new javax.swing.JButton();
        btUpdate = new javax.swing.JButton();
        btClear = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtDiscount = new javax.swing.JTextField();
        txtOrigin = new javax.swing.JTextField();
        txtSellPrice = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Category", "Name", "unitPrice", "Discount", "Origin", "sellPrice"
            }
        ));
        tbProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduct);

        btDelete.setText("Delete");

        jLabel1.setText("ID");

        lbCategory.setText("Category");

        lbProduct.setText("Name Product");

        lbUnitPrice.setText("unitPrice");

        lbDiscount.setText("discount");

        lbOrigin.setText("origin");

        lbSellPrice.setText("sellPrice");

        btAdd.setText("Add");
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btUpdate.setText("Update");

        btClear.setText("Clear");

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtUnitPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDiscount.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtOrigin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtSellPrice.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbCategory)
                            .addComponent(lbProduct)
                            .addComponent(lbUnitPrice)
                            .addComponent(lbDiscount)
                            .addComponent(lbOrigin)
                            .addComponent(lbSellPrice))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOrigin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiscount)
                            .addComponent(txtUnitPrice)
                            .addComponent(txtName)
                            .addComponent(txtID)
                            .addComponent(txtSellPrice)
                            .addComponent(cbCategory, 0, 153, Short.MAX_VALUE))
                        .addGap(244, 244, 244)
                        .addComponent(btAdd)
                        .addGap(30, 30, 30)
                        .addComponent(btUpdate)
                        .addGap(27, 27, 27)
                        .addComponent(btClear)
                        .addGap(33, 33, 33)
                        .addComponent(btDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbCategory)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduct)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUnitPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDiscount)
                    .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbOrigin)
                            .addComponent(txtOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSellPrice)
                            .addComponent(txtSellPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAdd)
                            .addComponent(btUpdate)
                            .addComponent(btClear)
                            .addComponent(btDelete))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProductMouseClicked
        int row = tbProduct.getSelectedRow();
        txtID.setText(String.valueOf(tbProduct.getValueAt(row, 0)));
        txtName.setText((String) tbProduct.getValueAt(row, 2));
        txtUnitPrice.setText(String.valueOf(tbProduct.getValueAt(row, 3)));
        txtDiscount.setText(String.valueOf(tbProduct.getValueAt(row, 4)));
        
    }//GEN-LAST:event_tbProductMouseClicked

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btAddActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btUpdate;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbDiscount;
    private javax.swing.JLabel lbOrigin;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbSellPrice;
    private javax.swing.JLabel lbUnitPrice;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrigin;
    private javax.swing.JTextField txtSellPrice;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables

    private void initProduct() {
        ProductDAO dao = new ProductDAO();
        try {
            List<Product> list = dao.getAllProduct();
            DefaultTableModel model = (DefaultTableModel) tbProduct.getModel();
            model.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                model.addRow(new Object[] { 
                    list.get(i).getId(),
                    list.get(i).getCategory().getName(),
                    list.get(i).getName(),
                    
                });
            }
        } catch (Exception e) {
        }
    }

    private void setLanguage() {
        btAdd.setText(bun.getString("add"));
        btClear.setText(bun.getString("clear"));
        btDelete.setText(bun.getString("delete"));
        btClear.setText(bun.getString("clear"));
        lbProduct.setText(bun.getString("NameProduct"));
    }
}
