/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Entity.Bill;
import Entity.StockInOutDetail;
import Model.BillDAO;
import Model.ProductDAO;
import Helper.JdbcHelper;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author ADMIN
 */
public class Reporting extends javax.swing.JDialog {
    JdbcHelper dbConn = null;
    Locale loca = null;
    ResourceBundle bun = null;
    /**
     * Creates new form Reporting
     */
    public Reporting(java.awt.Frame parent, boolean modal, JdbcHelper dbconn, Locale loca, ResourceBundle bun) {
        super(parent, modal);
        initComponents();
        this.dbConn = dbconn;
        this.loca = loca;
        this.bun = bun;
        setLanguage();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listTopSelling = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        txtSelling = new javax.swing.JTextField();
        btTopProduct = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBill = new javax.swing.JTextField();
        btBill = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        topBill = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        txtLeast = new javax.swing.JTextField();
        btProductLeast = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        topSoldLeast = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listTopSelling);

        jLabel1.setText("Top  selling products");

        txtSelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSellingActionPerformed(evt);
            }
        });

        btTopProduct.setText("Search");
        btTopProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTopProductActionPerformed(evt);
            }
        });

        jLabel2.setText("bills with the highest total");

        btBill.setText("Search");
        btBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBillActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(topBill);

        jLabel3.setText("products sold at least");

        btProductLeast.setText("Search");
        btProductLeast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductLeastActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(topSoldLeast);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLeast, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSelling, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btTopProduct)
                        .addGap(123, 123, 123)
                        .addComponent(btBill)
                        .addGap(223, 223, 223)
                        .addComponent(btProductLeast)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtLeast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTopProduct)
                    .addComponent(btBill)
                    .addComponent(btProductLeast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSellingActionPerformed
        
    }//GEN-LAST:event_txtSellingActionPerformed

    private void btTopProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTopProductActionPerformed
        try {
            ProductDAO dao = new ProductDAO();
            int num = Integer.parseInt(txtSelling.getText());
            List<StockInOutDetail> list = dao.getTopSellingProduct(num);
            DefaultListModel<String> model = new DefaultListModel<>();
            model.clear();
            model.addElement("Product ID           Total");
            for (StockInOutDetail st : list) {
                model.addElement(st.getProduct().getId()+"            "+st.getTotalOut());
            }
            listTopSelling.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btTopProductActionPerformed

    private void btBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBillActionPerformed
        try {
            BillDAO dao = new BillDAO();
            int num = Integer.parseInt(txtBill.getText());
            List<Bill> list = dao.getTopBill(num);
            DefaultListModel<String> model = new DefaultListModel<>();
            model.clear();
            model.addElement("Bill ID           Total");
            for (Bill bill : list) {
                model.addElement(bill.getId()+"       "+bill.getTotal());
            }
            topBill.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btBillActionPerformed

    private void btProductLeastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductLeastActionPerformed
         try {
            int num = Integer.parseInt(txtSelling.getText());
            
            List<StockInOutDetail> list = new ProductDAO().getLeastSellingProduct(num);
            DefaultListModel<String> model = new DefaultListModel<>();
            model.clear();
            model.addElement("Product ID           Total");
            for (StockInOutDetail st : list) {
                model.addElement(st.getProduct().getId()+"            "+st.getTotalOut());
            }
            listTopSelling.setModel(model);
        } catch (Exception ex) {
            Logger.getLogger(Reporting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btProductLeastActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBill;
    private javax.swing.JButton btProductLeast;
    private javax.swing.JButton btTopProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listTopSelling;
    private javax.swing.JList<String> topBill;
    private javax.swing.JList<String> topSoldLeast;
    private javax.swing.JTextField txtBill;
    private javax.swing.JTextField txtLeast;
    private javax.swing.JTextField txtSelling;
    // End of variables declaration//GEN-END:variables

    private void setLanguage() {
    }
}
